<a href="https://colab.research.google.com/github/abhishekmishra-bareilly/Deep-Learning/blob/main/Sentiment_analysis_using_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Import the dependancy
import pandas as pd
import numpy as np

In [5]:
# Load the dataset
data1 = pd.read_csv('/content/drive/MyDrive/Copy of User Reviews.csv')

In [6]:
data1.head(5)

App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
1  10 Best Foods for You    This help eating healthy exercise regular basis   
2  10 Best Foods for You                                                NaN   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
2       NaN                 NaN                     NaN  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000

In [7]:
#Shape of the dataset
data1.shape

(64295, 5)

In [8]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   App                     64295 non-null  object 
 1   Translated_Review       37427 non-null  object 
 2   Sentiment               37432 non-null  object 
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB


In [9]:
# dropping column with all null values
newdata = data1.dropna()

In [10]:
newdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37427 entries, 0 to 64230
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   App                     37427 non-null  object 
 1   Translated_Review       37427 non-null  object 
 2   Sentiment               37427 non-null  object 
 3   Sentiment_Polarity      37427 non-null  float64
 4   Sentiment_Subjectivity  37427 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.7+ MB


In [11]:
# Put only two columns for analysis
data = newdata[['Translated_Review','Sentiment']]

In [12]:
data.head()

Translated_Review Sentiment
0  I like eat delicious food. That's I'm cooking ...  Positive
1    This help eating healthy exercise regular basis  Positive
3         Works great especially going grocery store  Positive
4                                       Best idea us  Positive
5                                           Best way  Positive

In [13]:
# Check for duplicate values
data.duplicated().sum()

9433

In [14]:
 # Drop duplicate values
 data.drop_duplicates(inplace=True)

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


In [15]:
# Again check the shape
data.shape

(27994, 2)

In [16]:
# Again Check for duplicate values
data.duplicated().sum()

0

### Data preprocessing

#### remove all html tags

In [17]:
# Create function to remove all html tags
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [18]:
data['Translated_Review'] = data['Translated_Review'].apply(remove_html_tags)

<ipython-input-18-10f916cac060>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Translated_Review'] = data['Translated_Review'].apply(remove_html_tags)


#### Convert into lowercase

In [19]:
# Convert into lowercase
data['Translated_Review'] = data['Translated_Review'].str.lower()

<ipython-input-19-58d604997eb5>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Translated_Review'] = data['Translated_Review'].str.lower()


In [20]:
data['Translated_Review'].head()

0    i like eat delicious food. that's i'm cooking ...
1      this help eating healthy exercise regular basis
3           works great especially going grocery store
4                                         best idea us
5                                             best way
Name: Translated_Review, dtype: object

#### Remove stopwords

In [21]:
# Remove stopwords
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [23]:
# Applying function
data['Translated_Review'] = data['Translated_Review'].apply(remove_stopwords)

<ipython-input-23-31db0998ea00>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Translated_Review'] = data['Translated_Review'].apply(remove_stopwords)


In [24]:
data['Translated_Review'].head()

0     like eat delicious food. that's i'm cooking f...
1           help eating healthy exercise regular basis
3           works great especially going grocery store
4                                         best idea us
5                                             best way
Name: Translated_Review, dtype: object

In [25]:
#Split labels and features
x = data.iloc[:,0:1]
y = data['Sentiment']

In [26]:
x

Translated_Review
0       like eat delicious food. that's i'm cooking f...
1             help eating healthy exercise regular basis
3             works great especially going grocery store
4                                           best idea us
5                                               best way
...                                                  ...
64222   ads older many agents ..not much owner posted...
64223   photos posted portal load, fit purpose. i'm s...
64226  dumb app,  wanted post property rent give opti...
64227   property business got link sms happy performa...
64230  useless app,  searched flats kondapur, hyderab...

[27994 rows x 1 columns]

In [27]:
y

0        Positive
1        Positive
3        Positive
4        Positive
5        Positive
           ...   
64222    Positive
64223    Positive
64226    Negative
64227    Positive
64230    Negative
Name: Sentiment, Length: 27994, dtype: object

### label incoding

In [28]:
# Using label incoding
from sklearn.preprocessing import LabelEncoder
enco = LabelEncoder()

y = enco.fit_transform(y)

In [29]:
y

array([2, 2, 2, ..., 0, 2, 0])

In [30]:
# Train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 2)

In [31]:
y_train.shape

(25194,)

### Applying bag of words

In [32]:
# Applying bow
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [38]:
x_train_bow = cv.fit_transform(x_train['Translated_Review']).toarray()
x_test_bow = cv.transform(x_test['Translated_Review']).toarray()

In [39]:
x_test_bow.shape

(2800, 20100)

In [40]:
x_train_bow.shape

(25194, 20100)

#### GaussianNB

In [41]:
# Using gausian algorithm
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
gd = GaussianNB()

gd.fit(x_train_bow,y_train)

GaussianNB()

In [42]:
y_pred = gd.predict(x_test_bow)

In [43]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.38821428571428573

In [44]:
confusion_matrix(y_test,y_pred)

array([[315, 168, 145],
       [ 93, 241,  76],
       [710, 521, 531]])

#### random forest algo

In [54]:
# Using random forest algo
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [55]:
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [58]:
y_pred_rf = rf.predict(x_test_bow)

In [59]:
accuracy_score(y_test,y_pred_rf)

0.8528571428571429

In [60]:
confusion_matrix(y_test,y_pred_rf)

array([[ 356,   32,  240],
       [   7,  350,   53],
       [  37,   43, 1682]])