<a href="https://colab.research.google.com/github/abhishekmishra-bareilly/Deep-Learning/blob/main/backpropagation_(regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Store the data

In [4]:
data = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
data

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [21]:
x = data.iloc[:,0:-1].values
y = data['lpa'].values

In [19]:
x

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]])

## Applying model

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [8]:
model = Sequential()

model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

In [10]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [12]:
# Check for weight
model.get_weights()

[array([[ 0.71340895,  0.9027542 ],
        [-0.901318  ,  0.3274597 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.4128368],
        [ 1.1904329]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
# Creating an optimizer
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss = 'mean_squared_error',optimizer=optimizer)

In [23]:
model.fit(x,y,epochs=205,verbose=1,batch_size=1)

Epoch 1/205
4/4 [==============================] - 0s 3ms/step - loss: 1.9773
Epoch 2/205
4/4 [==============================] - 0s 3ms/step - loss: 1.9231
Epoch 3/205
4/4 [==============================] - 0s 4ms/step - loss: 1.8875
Epoch 4/205
4/4 [==============================] - 0s 4ms/step - loss: 1.8289
Epoch 5/205
4/4 [==============================] - 0s 3ms/step - loss: 1.7821
Epoch 6/205
4/4 [==============================] - 0s 3ms/step - loss: 1.7436
Epoch 7/205
4/4 [==============================] - 0s 3ms/step - loss: 1.7201
Epoch 8/205
4/4 [==============================] - 0s 3ms/step - loss: 1.6671
Epoch 9/205
4/4 [==============================] - 0s 3ms/step - loss: 1.6436
Epoch 10/205
4/4 [==============================] - 0s 3ms/step - loss: 1.5996
Epoch 11/205
4/4 [==============================] - 0s 3ms/step - loss: 1.5736
Epoch 12/205
4/4 [==============================] - 0s 3ms/step - loss: 1.5368
Epoch 13/205
4/4 [==============================] - 0s 3ms/st

In [25]:
# Check for new weights
model.get_weights()

[array([[ 0.9667076 ,  0.65247977],
        [-0.7423183 ,  0.1523974 ]], dtype=float32),
 array([ 0.20796767, -0.2148689 ], dtype=float32),
 array([[-0.50255  ],
        [ 0.9737795]], dtype=float32),
 array([-0.22639425], dtype=float32)]