<a href="https://colab.research.google.com/github/abhishekmishra-bareilly/Deep-Learning/blob/main/backpropagation(classification).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
data

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
x = data.iloc[:,0:-1].values
y = data['lpa'].values

In [5]:
x

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]])

## Applying model

In [6]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model = Sequential()

model.add(Dense(2,activation='sigmoid', input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [9]:
# Check for weight
model.get_weights()

[array([[-0.7296165 , -0.20594811],
        [-1.0183647 , -1.0521312 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.41271067],
        [-0.8671107 ]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
# Creating an optimizer
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss = 'binary_crossentropy',optimizer=optimizer)

In [11]:
model.fit(x,y,epochs=205,verbose=1,batch_size=1)

Epoch 1/205
4/4 [==============================] - 1s 6ms/step - loss: 0.6855
Epoch 2/205
4/4 [==============================] - 0s 5ms/step - loss: 0.6673
Epoch 3/205
4/4 [==============================] - 0s 25ms/step - loss: 0.6458
Epoch 4/205
4/4 [==============================] - 0s 15ms/step - loss: 0.6278
Epoch 5/205
4/4 [==============================] - 0s 9ms/step - loss: 0.6082
Epoch 6/205
4/4 [==============================] - 0s 8ms/step - loss: 0.5891
Epoch 7/205
4/4 [==============================] - 0s 9ms/step - loss: 0.5691
Epoch 8/205
4/4 [==============================] - 0s 10ms/step - loss: 0.5499
Epoch 9/205
4/4 [==============================] - 0s 10ms/step - loss: 0.5290
Epoch 10/205
4/4 [==============================] - 0s 12ms/step - loss: 0.5111
Epoch 11/205
4/4 [==============================] - 0s 12ms/step - loss: 0.4903
Epoch 12/205
4/4 [==============================] - 0s 7ms/step - loss: 0.4710
Epoch 13/205
4/4 [==============================] - 0s 