<a href="https://colab.research.google.com/github/abhishekmishrabareilly/Deep-Learning/blob/main/python_100_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q - find out the data types and count only int type of data**

In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/PYTHON/colab with data/automobile/automobile_data.csv')

In [6]:
data.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [12]:
data.dtypes.value_counts()

object     16
int64       5
float64     5
dtype: int64

In [23]:
new_data = data.select_dtypes(include = ['int64','float64'])
new_data.dtypes.value_counts()

int64      5
float64    5
dtype: int64

**Q - find top 5 highlly corelated varibles**


In [26]:
correlations = data.corr().unstack().sort_values(ascending=False)

In [27]:
correlations[correlations >= correlations.iloc[1]]

symboling          symboling            1.0
wheel-base         wheel-base           1.0
city-mpg           city-mpg             1.0
compression-ratio  compression-ratio    1.0
engine-size        engine-size          1.0
curb-weight        curb-weight          1.0
height             height               1.0
width              width                1.0
length             length               1.0
highway-mpg        highway-mpg          1.0
dtype: float64

### **Q- key features of python**

* it is free and open source language
* it hase clear syntex to understanding
* easy to fixing errors
* it is object orianted language

### **Q - how many keywords in python**
* keywords are resurved words, there are 33 keywords in python like- if, else, for, return, true, false, none, def etc

### **Q - what are literals in python**
* string literals - sequence of the charectors
* numbers literals - integer, float, complex numbers
* booleean literals - true or false
* spacial literals none is the good example

###**Q  - how to concat two tuples**

In [28]:
tup1 = (1,'a',True)
tup2 = (4,5,6)
c = tup1 + tup2
c

(1, 'a', True, 4, 5, 6)

### **Q5 - what are functions in python**
* function is the pice of code that can be re use in the program
* python have pre build function like print(), pop()
* also it allowes to build function from the user using **def**

### **Q6 - initialize 5*5 numpy array with only zero**

In [31]:
import numpy as np
n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###**Q7 - what is pandas?**
* it can help to deal with large variety of files using **series** and **DataFrame**

### **Q8 - what are dataframe?**
* data frames are mutable datatypes present in the pandas libarary Also we can store many type of data
* like read csv file using **pd.read_csv('my_data.csv')**

### **Q9- what is pandas series**
* seriese is a **one dimensional pandas datastructure** that support almost any types of data

In [35]:
data = ['1',2,'three',4.0]
s = pd.Series(data)
print(s)
print(type(s))

0        1
1        2
2    three
3      4.0
dtype: object
<class 'pandas.core.series.Series'>


### **Q10 - what is the use of groupby() function**
* it is use to take set of information and gives groupped information

### **Q11- how to create a dataframe from list**

In [44]:
import pandas as pd

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
df = pd.DataFrame(data, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### **Q12- how to create dataframe" from dictonary**

In [45]:
bikes = [1,2,3]
car = ['mahindra', 'kia', 'tata']
d = {'car':car,'bikes':bikes}
data = pd.DataFrame(d)
data

car  bikes
0  mahindra      1
1       kia      2
2      tata      3

### **Q13 - how to combine dataframe using join() function**
* when we want to combine diffrent dataframe **horizontally**  then we use join function
* pandas support left, right, inner, right, and outer joints

### **Q14 - which methosd works best for vertically stacking of dataframe**
* we can use **concat** when we having same columns from both dataframes

### **Q15 - how to merse dataframe in pandas**
* merse depends the key and fields of the diffrent dataframe
* if the data have similar field then use axis 0
* if the data have diffrent fields then use axis 1


In [46]:
import pandas as pd

left_df = pd.DataFrame({
    "key": [1, 2, 3, 4],
    "left_value": ["A", "B", "C", "D"]
})

right_df = pd.DataFrame({
    "key": [3, 4, 5, 6],
    "right_value": ["X", "Y", "Z", "W"]
})

mearsing_data = pd.merge(left_df,right_df, on = 'key')

print(mearsing_data)

   key left_value right_value
0    3          C           X
1    4          D           Y


### **Q16- how to drop NAN in pandas**

In [48]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Abhishek Mishra EDA capstone project 1/Airbnb NYC 2019.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              48895 non-null  int64  
 1   name                            48879 non-null  object 
 2   host_id                         48895 non-null  int64  
 3   host_name                       48874 non-null  object 
 4   neighbourhood_group             48895 non-null  object 
 5   neighbourhood                   48895 non-null  object 
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object 
 9   price                           48895 non-null  int64  
 10  minimum_nights                  48895 non-null  int64  
 11  number_of_reviews               48895 non-null  int64  
 12  last_review                     

In [51]:
new_data = data.dropna()
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38821 entries, 0 to 48852
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              38821 non-null  int64  
 1   name                            38821 non-null  object 
 2   host_id                         38821 non-null  int64  
 3   host_name                       38821 non-null  object 
 4   neighbourhood_group             38821 non-null  object 
 5   neighbourhood                   38821 non-null  object 
 6   latitude                        38821 non-null  float64
 7   longitude                       38821 non-null  float64
 8   room_type                       38821 non-null  object 
 9   price                           38821 non-null  int64  
 10  minimum_nights                  38821 non-null  int64  
 11  number_of_reviews               38821 non-null  int64  
 12  last_review                     

###**Q17 - how to access data using value index**
* Using loc we can do this 

In [54]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})

df = df.set_index("A")
print(df)
print(' ')
print(' ')
print(df.loc[2])


   B  C
A      
1  4  7
2  5  8
3  6  9
 
 
B    5
C    8
Name: 2, dtype: int64


### **Q18 - how to add single line and multiline comment in python**
* single line - #
* multiline comment - """your comments"""

In [ ]:
# single line

""" multiline comment
multiline comment
multiline comment"""

### **Q19 - can we add eliment in tuple**
* no we can not because tuple is immutable

### **Q20 - what is dictionary in python**
* dictonary is the collection of items in no particular order

### **Q21- wind central tendancy of [10,20,30,40,50,60]**

In [56]:
data = np.array([10,20,30,30,40,50,60])

print(np.mean(data))
print(np.median(data))
print(np.std(data))

34.285714285714285
30.0
15.90789817951435


### **Q22 - what is use of the classifier**
* it use to predict the class

### **Q23 - how to convert lowercase**

In [57]:
data = 'I AM ABHISHEK MISHRA'

print(data.lower())

i am abhishek mishra


### **Q24 - how to get all the keyes in a dictonary**

In [59]:
my_dict = {
    "A": 1,
    "B": 2,
    "C": 3
}

k = my_dict.keys()

k


dict_keys(['A', 'B', 'C'])

### **Q25 - how to capitalize fist letter in a string**

In [60]:
string = 'abhishek'

print(string.capitalize())

Abhishek


### **Q26 - how to insert an eliment at given index in python**
* by using insert()

In [61]:
list = [0, 1, 2, 3, 4, 5, 6, 7, 8]

list.insert(6,10) # insert 10 in 6th index
list

[0, 1, 2, 3, 4, 5, 10, 6, 7, 8]

### **Q27 - how to remove duplicate from list**
* we can remove duplicats using set

In [66]:
list1 = [3,3,4,5,5,6,7,8]

new_list = set(list1)
print(new_list)

{3, 4, 5, 6, 7, 8}


### **Q28 - what is recursion?**
* the basic mean of recursion is the function calling itself
* if we use recursion in a loop then we need to mension terminated otherwise recursion all itself till infinite.

###**Q29- write down a function to find fectorial**

In [76]:
def fectorial(n):
  if n == 1:
    return 1

  else:
    return (n * fectorial(n-1))


print(fectorial(3))

6


### **Q30 - what is list comprehension?**
* it is use for transforming one list into another list.

In [77]:
a = [i for i in range(100)]

print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


### **Q31 - why we use bytes() function**
* it return bytes object

### **Q32 - what are the diffrent types of operators in python**
* arthmetic operation -   +, -, *, /, %, **, //
* relational operation -    ==, !=, >, <, >=, <=
* assignment operation -   =, +=, -=, *=, /=, %=, **=, //=
* logical operation -   and, or, not

### **Q33 - what is with statement used for in python?**
* it use for exception handaling.
* it makes the code more esy to read.

###**Q34 - what is map() function in python**
* it use to apply function on all the eliment.

In [81]:
def mul3(n):
  return n*3

num = (1,2,3,4,5,6,7)
result = map(mul3,num)
print(set(result))

{3, 6, 9, 12, 15, 18, 21}


### **Q35 - what is __init__ in python**
* __init__ is use to create the class
* it is reserved method in python

### **Q36 - what is the diffrence b/w tupel and dictonary**
* tupel is immuatable, can not manupulate the eliments in the tupel
* dictonary is mutable

### **Q37 - what is pass in python**
* pass do nothing, it is null statment.
* it is use when you do not have any statment but still you need to mension a statment

### **Q38 - how can an object can be coppyed in python?**
* we can use  = operator to copy the object variable
* also can use .copy()

### **Q39 - how can a number converted into string?**

In [84]:
n = 10
new_n =str(n)
print(new_n)
print(type(new_n))

10
<class 'str'>


### **Q40 - what are the module and packages in python?**
* module mean is the structure of a program.

* pacckage the folder where the program present with multiple module.

### **Q41 - difference b/w numpy and scipy**
* numpy(numerical python) is use for simple mathmetical problems.

* scipy (scientific python) is use for complex numerical problems.

### **Q42 - what is encapsulation in python**
* it means binding the small codes.

* Example - class

### **Q43 - what is split function dose in python?**
* it split entire data according to the condition

In [86]:
string = ('i, am, abhishek mishra')
n = string.split(',')
print(n)

['i', ' am', ' abhishek mishra']


### **Q44 - what is docstring in python?**
* it use to describe the functionality of the particular function, class
* it is define right after the definition of a function, method, class


### **Q45 - what is the use of a lambda function**

* it serve as nameless function that are needed for short periods of time.


In [87]:
triple = lambda x: x * 3
 
print(triple(4))

12


### **Q46 - cn you denote the working of the bool() function**

In [90]:
a = 10
b = 0
c = 15

print(bool(a))
print(bool(b))
print(bool(c))

True
False
True


## **intermediat questions**

### **Q47 - how to create a new column in pandas using the values from other columns**

In [95]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]})
df['SUM'] = df['A']+df['B']+df['C']
df

A  B  C  SUM
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

## **Q48 - what are the diffrent function can be used by groupby() in pandas?**
* sum(), mean(), max(), min(), count(), std()

### **Q49 - how to drop column from the data**

In [96]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]})

df.drop(columns = 'A',inplace=True)
df

B  C
0  4  7
1  5  8
2  6  9

### **Q50 - drop the row having column values as 7**

In [99]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]})


df = df[df.C!=7]
df

A  B  C
1  2  5  8
2  3  6  9

### **Q51 - find out highest paid player in each college team**

In [ ]:
df.groupby(['team','college'])['salary'].max()

### **Q52 - what is reindexing in pandas**
* reassing the entire index

In [100]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]})

d = [10,20,30]
df.index = d
df

A  B  C
10  1  4  7
20  2  5  8
30  3  6  9

### **Q53 - create a lambda function which can add all of them [5,8,20,50,100]**

In [107]:
a = [5,8,20,50,100]
k=0
for i in a:
  k=i+k

print(k)

# Using lambda
from functools import reduce

sum = reduce(lambda x, y:x+y, a)
print(sum)

183
183


### **Q54 - what is Vstack in numpy?**
* basically it is use for adding two arrayes

In [108]:
n1 = np.array([11,2,34,14,54,5,6,7])
n2 = np.array([32,54,65,67,787,78,35,67])

print(np.vstack((n1,n2)))

[[ 11   2  34  14  54   5   6   7]
 [ 32  54  65  67 787  78  35  67]]


###**Q55- how is python code interpreted?**

* debugging can be done by line by line

### **Q56 - how to remove spaces from the string?**

In [109]:
a = 'i am abhishek mishra'
print(a.replace(' ',''))

iamabhishekmishra


###**Q57- explain the file processing modes that python supports?**

* read only(r)
* write only(w)
* read-write(rd)
* append(a)

### **Q58- what is pickling and unpickling?**
* pickling - it is the process to convert python object into byte stream for storing into the database.

* Unpickling - it is the reverse of pickling

## **Tricky question**

### **Q59 - how could you update the value of apple 10 to 100**

In [114]:
frouts = {'apple':10,'orange':30,'banana':60}
frouts['apple'] = 100
frouts

{'apple': 100, 'orange': 30, 'banana': 60}

### **Q60 - how to find comman elements present in the given two sets?**

In [116]:
s1 = {1,2,3,4,5}
s2 = {4,5,6,7,8}

print(s1.intersection(s2))
print(s1-s2)


{4, 5}
{1, 2, 3}


### **Q61 - find the number is a palindrome or not**

In [121]:
n = int(input('enter number:'))
n = str(n)
n1 = n[::-1]
if n == n1:
  print(f'{n} is palindrome')

else:
  print(f'{n} is not palindrome')


enter number:123
123 is not palindrome


### **Q62 - write a program that print following pattern**
1

2 2

3 3 3

4 4 4 4

5 5 5 5 5

In [124]:
for i in range(1, 6):
    for j in range(i):
        print(i, end=" ")
    print("")

a = [i in range (1,6)]
a

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


[True]

### **Q63 - write a program that print following pattern**
.#

.# #

.# # #

.# # # #

.# # # # #

In [127]:
for i in range(1, 6):
    for j in range(i):
      print("#", end=" ")
    print("")

# 
# # 
# # # 
# # # # 
# # # # # 


### **Q64 -  write a program that print following pattern**
0

0 1 

0 1 2 

0 1 2 3 

0 1 2 3 4 

In [128]:
for i in range(1, 6):
    for j in range(i):
      print(j, end=" ")
    print("")

0 
0 1 
0 1 2 
0 1 2 3 
0 1 2 3 4 


### **Q65 - print the pascal's tringle pattern**

In [129]:
def pascal_triangle(n):
    for i in range(n):
        C = 1
        for j in range(1, i+2):
            print(C, end=" ")
            C = int(C * (i - j + 1) / j)
        print("")

pascal_triangle(6)

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 


##**Q66 - how would you incriment the values of the dictonary**

In [132]:
d1 ={'A':10,'B':20,'C':30}

for i in d1.keys():
  d1[i] = d1[i]+1
  
d1.values()

dict_values([11, 21, 31])

### **Q67 - print randome number**

In [134]:
import random
print(random.random())

print(random.randint(10,20))

0.8575985450315736
17


### **Q68 - how to find ASCII value of a given cherector**

In [135]:
value = 'a'
print(ord(value))

97


### **Q69 - how to suffel the list**

### **Q70 - what will be the output**

In [2]:
list1 = [2,3,5,7,8]
print(list1*2)

[2, 3, 5, 7, 8, 2, 3, 5, 7, 8]


### **Q71 - how to check that the given number is armstrong or not**

In [39]:
x = str(input('Enter number'))
k = 0
for i in x:
  k=k+(int(i)**3)
k==int(x)

Enter number153


True

### **Q72 - how to check the perfect number**

In [44]:
num = 28
div = [i for i in range(1,num) if num%i ==0]
sum(div) == num

True

### **Q73 - how to check the number is strong**

In [62]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

In [67]:
x = str(145)
k = 0
for i in x:
  k = k + (factorial(int(i)))

k == int(x)

True

### **Q74 - how to find second highest number in the list**

In [76]:
sample_list = [1,2,3,4,5]
sample_list =set(sample_list)
sample_list.remove(max(sample_list))
max(sample_list)

4

### **Q75 - how to swap the fist and the last eliment in the list**

In [81]:
sample_list = [1,2,3,4,5]
a = sample_list[-1]
b = sample_list[0]

sample_list1 = sample_list
sample_list1[0] = a
sample_list1[-1] = b
print(sample_list1)

[5, 2, 3, 4, 1]


### **Q76 - write a program to count the vowels present in a string**





In [85]:
a = 'Abhishek'
vowel = ['A','a','E','e','I','i','O','o','U','U']
for i in a:
 if i in vowel:
   print(i)


A
i
e


### **Q77 - denote the working of exception**

In [90]:
try:
  x = 1/0
except:
  print('can not division by zero')


can not division by zero


### **Q78 - how does the finally block work in python**

In [94]:
try:
  x = 10/0
  print(x)
except:
  print('can not division by zero')
finally:
  print('this is finally working')

can not division by zero
this is finally working
